### ISSUE TITLE
Use this without telegram!?

### ISSUE THREAD

**Issue by mizzunet** [wrecker3000/Heroku-Mirror-Bot#1]
Can I somehow use this hot without telegram, say from the Heroku app website? Could you add support?

**Comment by wrecker3000** [comment]
Well there used to be a script for static website heroku app but heroku has completely banned that method as of now telegram is the most suitable method

**Comment by mizzunet** [comment]
> Well there used to be a script for static website heroku app but heroku has completely banned that method as of now telegram is the most suitable method

Ah, I understand. I don't use Telegram anymore.

Ignore this if I'm asking too much, by any chance, you make a bot for Matrix, it's ecosystem mostly same as Telegram.

**Comment by wrecker3000** [comment]
Well don't know about matrix will see in future when I get time

**Comment by mizzunet** [comment]
Thanks
